from __future__ import annotations

from html import escape
from pathlib import Path

from .drawio import COLORS, _display_brand, _icon_key, _icon_markup, _node_image_data
from .layout import Box, Layout, runtime_side_detour
from .model import Architecture, Node


def _node_svg(node: Node, box: Box, sketch: bool, theme: str) -> str:
    kind, label, subtitle = node.kind, node.label, node.subtitle
    fill, stroke = COLORS[kind]
    if theme == "brand-logos":
        fill, stroke = "#ffffff", "#94a3b8"
        dash = ""
        card_radius, card_width, tile_stroke = 9, 1.5, "#e2e8f0"
    else:
        dash = ' stroke-dasharray="5 3"' if sketch else ""
        card_radius, card_width, tile_stroke = 12, 2, stroke
    if theme in {"icon-sketch", "brand-logos"}:
        center_y = box.y + box.height / 2
        label_y = center_y - (6 if subtitle else 0)
        icon_y = center_y - 22
        brand = _display_brand(node, theme)
        if brand:
            icon = (
                f'<image x="{box.x + 23}" y="{icon_y + 7}" width="30" height="30" '
                f'href="{escape(_node_image_data(node, theme), quote=True)}"/>'
            )
        else:
            icon = (
                f'<svg x="{box.x + 20}" y="{icon_y + 4}" width="36" height="36" viewBox="0 0 48 48">'
                f'{_icon_markup(node)}</svg>'
            )
        return (
            f'<g data-icon="{_icon_key(node)}" data-brand="{brand.key if brand else ""}">'
            f'<rect x="{box.x}" y="{box.y}" width="{box.width}" height="{box.height}" '
            f'rx="{card_radius}" fill="{fill}" stroke="{stroke}" stroke-width="{card_width}"{dash}/>'
            f'<rect x="{box.x + 14}" y="{icon_y - 2}" width="48" height="48" rx="11" '
            f'fill="#ffffff" stroke="{tile_stroke}" stroke-width="1"/>'
            f'{icon}'
            f'<text x="{box.x + 76}" y="{label_y}" text-anchor="start" '
            f'font-family="Inter,Arial,sans-serif" font-size="15" font-weight="700" fill="#0f172a">'
            f'{escape(label)}</text>'
            + (
                f'<text x="{box.x + 76}" y="{label_y + 21}" text-anchor="start" '
                f'font-family="Inter,Arial,sans-serif" font-size="12" fill="#475569">'
                f'{escape(subtitle)}</text>'
                if subtitle
                else ""
            )
            + "</g>"
        )
    if kind == "database":
        shape = (
            f'<path d="M {box.x},{box.y + 12} Q {box.x},{box.y} {box.x + box.width / 2},{box.y} '
            f'Q {box.right},{box.y} {box.right},{box.y + 12} L {box.right},{box.bottom - 12} '
            f'Q {box.right},{box.bottom} {box.x + box.width / 2},{box.bottom} '
            f'Q {box.x},{box.bottom} {box.x},{box.bottom - 12} Z" fill="{fill}" stroke="{stroke}" '
            f'stroke-width="2"{dash}/>'
        )
    else:
        radius = 18 if kind == "cloud" else 10
        shape = (
            f'<rect x="{box.x}" y="{box.y}" width="{box.width}" height="{box.height}" '
            f'rx="{radius}" fill="{fill}" stroke="{stroke}" stroke-width="2"{dash}/>'
        )
    center_x, center_y = box.center
    label_y = center_y - (7 if subtitle else 0)
    text = (
        f'<text x="{center_x}" y="{label_y}" text-anchor="middle" '
        f'font-family="Inter,Arial,sans-serif" font-size="15" font-weight="700" fill="#0f172a">'
        f'{escape(label)}</text>'
    )
    if subtitle:
        text += (
            f'<text x="{center_x}" y="{label_y + 21}" text-anchor="middle" '
            f'font-family="Inter,Arial,sans-serif" font-size="12" fill="#475569">'
            f'{escape(subtitle)}</text>'
        )
    return shape + text


def render_svg(architecture: Architecture, layout: Layout, output: str | Path) -> Path:
    destination = Path(output)
    destination.parent.mkdir(parents=True, exist_ok=True)
    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{layout.width:.0f}" height="{layout.height:.0f}" '
        f'viewBox="0 0 {layout.width:.0f} {layout.height:.0f}" role="img" aria-labelledby="title desc" '
        f'data-theme="{architecture.theme}">',
        f'<title id="title">{escape(architecture.title)}</title>',
        '<desc id="desc">Editable architecture preview generated by repo2drawio</desc>',
        '<defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" '
        'markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#334155"/>'
        '</marker></defs>',
        '<rect width="100%" height="100%" fill="#ffffff"/>',
        f'<text x="{layout.width / 2:.1f}" y="48" text-anchor="middle" '
        'font-family="Inter,Arial,sans-serif" font-size="26" font-weight="700" fill="#0f172a">'
        f'{escape(architecture.title)}</text>',
    ]

    for group in architecture.groups:
        box = layout.groups[group.id]
        clean = architecture.theme == "brand-logos"
        dash = ' stroke-dasharray="6 4"' if architecture.sketch and not clean else ""
        group_stroke = "#cbd5e1" if clean else "#94a3b8"
        group_width = "1.5" if clean else "2"
        parts.append(
            f'<rect x="{box.x}" y="{box.y}" width="{box.width}" height="{box.height}" rx="14" '
            f'fill="#f8fafc" fill-opacity="0.72" stroke="{group_stroke}" '
            f'stroke-width="{group_width}"{dash}/>'
        )
        parts.append(
            f'<text x="{box.x + 16}" y="{box.y + 27}" font-family="Inter,Arial,sans-serif" '
            f'font-size="16" font-weight="700" fill="#334155">{escape(group.label)}</text>'
        )

    nodes_by_id = {node.id: node for node in architecture.nodes}
    feature_groups = {"domestic", "voucher", "assistant", "content"}
    feature_mode = bool(feature_groups & set(layout.groups)) and "infrastructure" in layout.groups
    for edge_index, edge in enumerate(architecture.edges):
        source = layout.nodes[edge.source]
        target = layout.nodes[edge.target]
        sx, sy = source.center
        tx, ty = target.center
        if architecture.direction in {"LR", "RL"}:
            sx = source.right if tx >= sx else source.x
            tx = target.x if tx >= sx else target.right
            source_node = nodes_by_id[edge.source]
            target_node = nodes_by_id[edge.target]
            target_group = layout.groups.get(target_node.parent or "")
            if feature_mode and target_node.parent == "integrations":
                mid = (sx + tx) / 2
                path = f"M {sx},{sy} L {mid},{sy} L {mid},{ty} L {tx},{ty}"
                label_x, label_y = mid, (sy + ty) / 2 - 8
            elif (
                feature_mode
                and source_node.parent == "runtime"
                and target_node.parent in feature_groups
                and target_group is not None
            ):
                sx, sy = source.center[0], source.bottom
                tx, ty = target.x, target.center[1]
                top_y = target_group.y - 24.0 - (edge_index % 5) * 9.0
                spine_x = target_group.x - 32.0 - (edge_index % 6) * 10.0
                path = (
                    f"M {sx},{sy} L {sx},{top_y} L {spine_x},{top_y} "
                    f"L {spine_x},{ty} L {tx},{ty}"
                )
                label_x, label_y = (spine_x + tx) / 2, ty - 8
            elif (
                feature_mode
                and source_node.parent in feature_groups
                and target_node.parent == "infrastructure"
            ):
                sx, sy = source.x, source.center[1]
                tx, ty = target.center[0], target.y
                spine_x = layout.groups[source_node.parent].x - 32.0 - (edge_index % 6) * 10.0
                top_y = layout.groups["infrastructure"].y - 24.0 - (edge_index % 6) * 9.0
                path = (
                    f"M {sx},{sy} L {spine_x},{sy} L {spine_x},{top_y} "
                    f"L {tx},{top_y} L {tx},{ty}"
                )
                label_x, label_y = (spine_x + tx) / 2, top_y - 8
            elif (
                feature_mode
                and source_node.parent == "runtime"
                and target_node.parent == "infrastructure"
            ):
                sx, sy = source.right, source.center[1]
                tx, ty = target.center[0], target.y
                spine_x = layout.groups["runtime"].right + 34.0 + (edge_index % 6) * 12.0
                top_y = layout.groups["infrastructure"].y - 24.0 - (edge_index % 6) * 9.0
                path = (
                    f"M {sx},{sy} L {spine_x},{sy} L {spine_x},{top_y} "
                    f"L {tx},{top_y} L {tx},{ty}"
                )
                label_x, label_y = (sx + spine_x) / 2, sy - 8
            elif (
                source_node.parent == "runtime"
                and target_node.parent not in {None, "runtime", "data", "integrations"}
                and target_group is not None
            ):
                sx, sy = source.center[0], source.bottom
                tx, ty = target.center[0], target.y
                mid = target_group.y - 28.0 - (edge_index % 7) * 12.0
                path = f"M {sx},{sy} L {sx},{mid} L {tx},{mid} L {tx},{ty}"
                label_x, label_y = (sx + tx) / 2, mid - 8
            elif (
                source_node.parent == target_node.parent
                and source_node.parent not in {None, "runtime", "data", "integrations"}
                and ty > sy
            ):
                sx, sy = source.center[0], source.bottom
                tx, ty = target.center[0], target.y
                mid = (sy + ty) / 2
                path = f"M {sx},{sy} L {sx},{mid} L {tx},{mid} L {tx},{ty}"
                label_x, label_y = (sx + tx) / 2, mid - 8
            elif (
                source_node.parent == "runtime"
                and target_node.parent in {"data", "integrations"}
                and "runtime" in layout.groups
            ):
                mid = layout.groups["runtime"].right + 76.0 + edge_index * 18.0
                detour = runtime_side_detour(layout, edge.source)
                if detour is not None:
                    sx, sy = source.center[0], source.bottom
                    path = f"M {sx},{sy} L {sx},{detour} L {mid},{detour} L {mid},{ty} L {tx},{ty}"
                    label_x, label_y = (sx + mid) / 2, detour - 8
                else:
                    path = f"M {sx},{sy} L {mid},{sy} L {mid},{ty} L {tx},{ty}"
                    label_x, label_y = (sx + mid) / 2, sy - 8
            elif (
                source_node.parent not in {None, "runtime", "data", "integrations"}
                and target_node.parent in {"data", "integrations"}
            ):
                sx, sy = source.center[0], source.bottom
                detail_bottom = max(
                    (
                        box.bottom
                        for group_id, box in layout.groups.items()
                        if group_id not in {"runtime", "data", "integrations"}
                    ),
                    default=source.bottom,
                )
                bottom_y = detail_bottom + 42.0 + edge_index * 10.0
                side_left = min(
                    (
                        box.x
                        for group_id, box in layout.groups.items()
                        if group_id in {"data", "integrations"}
                    ),
                    default=target.x,
                )
                corridor_x = side_left - 62.0 - edge_index * 12.0
                path = (
                    f"M {sx},{sy} L {sx},{bottom_y} L {corridor_x},{bottom_y} "
                    f"L {corridor_x},{ty} L {tx},{ty}"
                )
                label_x, label_y = (corridor_x + tx) / 2, ty - 8
            else:
                mid = (sx + tx) / 2
                path = f"M {sx},{sy} L {mid},{sy} L {mid},{ty} L {tx},{ty}"
                label_x, label_y = mid, (sy + ty) / 2 - 8
        else:
            sy = source.bottom if ty >= sy else source.y
            ty = target.y if ty >= sy else target.bottom
            mid = (sy + ty) / 2
            path = f"M {sx},{sy} L {sx},{mid} L {tx},{mid} L {tx},{ty}"
            label_x, label_y = (sx + tx) / 2, mid - 8
        edge_stroke = "#475569" if architecture.theme == "brand-logos" else "#334155"
        edge_width = "1.5" if architecture.theme == "brand-logos" else "2"
        parts.append(
            f'<path d="{path}" fill="none" stroke="{edge_stroke}" stroke-width="{edge_width}" '
            'stroke-linejoin="miter" marker-end="url(#arrow)"/>'
        )
        if edge.label:
            parts.append(
                f'<text x="{label_x}" y="{label_y}" text-anchor="middle" '
                'font-family="Inter,Arial,sans-serif" font-size="12" fill="#334155" '
                f'stroke="#ffffff" stroke-width="4" paint-order="stroke">{escape(edge.label)}</text>'
            )

    for node in architecture.nodes:
        parts.append(_node_svg(node, layout.nodes[node.id], architecture.sketch, architecture.theme))

    parts.append("</svg>")
    destination.write_text("\n".join(parts) + "\n", encoding="utf-8")
    return destination
